---
inherit_from:
  - .niftany/layout.yml
  - .niftany/lint.yml
  - .niftany/metrics.yml
  - .niftany/naming.yml
  - .niftany/niftany_rubocop_rspec.yml
  - .niftany/performance.yml
  - .niftany/style.yml
  - .rubocop_todo.yml

require: [rubocop-rspec, rubocop-performance]

AllCops:
  DisplayCopNames: true
  NewCops: enable


Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'psu_identity.gemspec'

Style/OpenStructUse:
  Exclude:
    - 'lib/psu_identity/search_service/atomic_link.rb'
    - 'spec/lib/psu_identity/search_service/atomic_link_spec.rb'

Rspec/NestedGroups:
  Exclude:
    - 'spec/lib/psu_identity/search_service/person_spec.rb'
